name: Build-CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install --frozen-lockfile
      - run: yarn nx run-many --target=lint --all
      - run: yarn nx run-many --target=test --all --ci --code-coverage
      - run: yarn nx run-many --target=build --all
